### ISSUE TITLE
Not working! and Integration with Cucumber

### ISSUE THREAD

**Issue by salunkhe-ravi** [grasshopper7/extentreports-pdf-dashboard-reporter#1]
Hello @grasshopper7 ,

First of all would really appreciate your efforts and the idea of having a "pdf" based Extent report. Awesome!

Tried adding this one to my Cucumber based framework but it doesn't work.! Can you please provide more documentation on this one?.
Also, does it have any integration with Cucumber to start with ?

**Comment by grasshopper7** [comment]
I have integrated it with the extentreports-cucumber-maven plugin. Sample implementation is here - https://github.com/grasshopper7/extentreports-cucumberjson-report. The plugin repo - https://github.com/grasshopper7/extentreports-cucumberjson-plugin. U can check this issue for more details - https://github.com/grasshopper7/extentreports-cucumber5-adapter/issues/15

I am working on integrating this with the cucumber adapters. This is a sample of the new report i plan on using. 
[index.pdf](https://github.com/grasshopper7/extentreports-pdf-dashboard-reporter/files/5342090/index.pdf)

I am facing issues in adding this to extentreports, as extent does not process hooks correctly. Hopefully will have an initial release next week. Also plan to release this report to be used as a cucumber runner plugin, independent of extent. 

No licensing issues, as all the software packages used are Apache or MIT.

**Comment by grasshopper7** [comment]
This is now integrated with cucumber 6 (v 2.2.0) and cucumber 5 (v 2.1.0) adapters. Working on the documentation aspect. U can check the reference projects. for 6 - https://github.com/grasshopper7/extentreports-cucumber6-adapter and for 5 - https://github.com/grasshopper7/cuke5-extent-adapter-report.

It is now much more than a dashboard. Below is the summary page screen. Other screens are features, scenarios and detailed sections.

![summary](https://user-images.githubusercontent.com/10829355/97070455-e64e6400-15f5-11eb-9f3c-2f2bfc0b0cbb.png)
